---
title: "Cabezon"
output: html_document
date: "2023-06-22"
---

Install viridis package
```{r}
install.packages("viridis")
```

Load packages
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
#library(viridis)
```

Read in data
```{r}
fishbrain <- read_csv("fishbrain.csv")
#View(fishbrain)
recfin <- read_csv("recfin.csv")
#View(recfin)
recfin_bio <- read_csv("recfin_bio.csv")
#View(recfin_bio)
```

Edit Fishbrain data
```{r}
fish_ca <- fishbrain %>% 
  filter(latitude > 34.45) %>% 
  mutate(district = case_when(latitude > 34.45 & latitude < 37.18 ~ 'Central',
                              latitude >= 37.18 & latitude < 38.91 ~ 'Bay Area',
                              latitude > 38.91 & latitude < 40.44 ~ 'Wine',
                              latitude > 40.44 ~ 'Redwood')) %>% 
  separate(caught_at_local_time, c('year', 'month', 'day')) %>%  
  filter(common_name == "Cabezon") %>% 
  mutate(length_in_cm = length_in_m * 100) %>% 
  mutate_at(vars(district), as.factor) %>% 
  mutate(Sex = "F") %>% 
  mutate(district = fct_relevel(district, c("Central", "Bay Area", "Wine", "Redwood")))
#View(fish_ca)
```

Edit RecFIN Data
```{r}
recfin_ca <- recfin_bio %>% 
  filter(grepl("CENTRAL", RECFIN_PORT_NAME) | grepl("BAY AREA", RECFIN_PORT_NAME) | grepl("WINE", RECFIN_PORT_NAME) | grepl("REDWOOD", RECFIN_PORT_NAME)) %>% 
  filter(SPECIES_NAME == "CABEZON") %>% 
  separate(RECFIN_DATE, c("month", "day", "year")) %>% 
  mutate(district = case_when(grepl("CENTRAL", RECFIN_PORT_NAME) ~ "Central",
                              grepl("BAY AREA", RECFIN_PORT_NAME) ~ "Bay Area",
                              grepl("WINE", RECFIN_PORT_NAME) ~ "Wine",
                              grepl("REDWOOD", RECFIN_PORT_NAME) ~ "Redwood",
                              .default = RECFIN_PORT_NAME)) %>% 
  mutate_at(vars(district), as.factor) %>% 
  mutate(district = fct_relevel(district, c("Central", "Bay Area", "Wine", "Redwood"))) %>% 
  mutate(recfin_length_cm = RECFIN_LENGTH_MM / 10) %>% 
  mutate(Sex = "F")
#View(recfin_ca)
```

Count by district
```{r}
#Fishbrain
ca_fb_dis <- fish_ca %>% 
  group_by(district) %>% 
  tally()
View(ca_fb_dis)

#RecFIN
ca_rf_dis <- recfin %>% 
  group_by(DISTRICT_NAME) %>% 
  tally()
View(ca_rf_dis)
```

Length and weight analyses 
```{r}
#Length by district - Fishbrain
fish_ca %>% 
  ggplot(aes(district, length_in_cm)) +
  geom_boxplot() +
  labs(x = "District", y = "Length (cm)")
#Length by district - RecFIN
recfin_ca %>% 
  ggplot(aes(district, recfin_length_cm)) + 
  geom_boxplot() + 
  labs(x = "District", y = "Length (cm)")

#Weight by district - Fishbrain
fish_ca %>% 
  ggplot(aes(district, weight_in_kg)) +
  geom_boxplot() +
  ylim(0, 8) +
  labs(x = "District", y = "Weight (kg)")
#Weight by district - RecFIN
recfin_ca %>% 
  ggplot(aes(district, AGENCY_WEIGHT)) + 
  geom_boxplot() + 
  labs(x = "District", y = "Weight (kg)")

#Weight-length relationship - Fishbrain
fish_ca %>% 
  ggplot(aes(length_in_cm, weight_in_kg)) +
  geom_point() +
  ylim(0, 8) +
  labs(x = "Length (cm)", y = "Weight (kg)")
ca_ests <- estimate_weight_length(
  data = fish_ca,
  col_length = "length_in_cm",
  col_weight = "weight_in_kg")
View(ca_ests)
#Weight-length relationship - RecFIN
recfin_ca %>% 
  ggplot(aes(recfin_length_cm, AGENCY_WEIGHT)) +
  geom_point() +
  labs(x = "Length (cm)", y = "Weight (kg)")
recfin_ests <- estimate_weight_length(
  data = recfin_ca,
  col_length = "recfin_length_cm",
  col_weight = "AGENCY_WEIGHT")
View(recfin_ests)

length <- seq(0, 100, 1)
par(mfrow = c(1, 2))
plot(length, ca_ests$A[2] * length ^ ca_ests$B[2], type = 'l', col = 'black', lwd = 5, xlab = "Length (cm)", ylab = "Weight (kg)")
points(fish_ca$length_in_cm, fish_ca$weight_in_kg, col = alpha('black', 0.2), pch = 1)
lines(length, recfin_ests$A[2] * length ^ recfin_ests$B[2], col = 'blue', lwd = 5)
plot(length, ca_ests$A[2] * length ^ ca_ests$B[2], type = 'l', col = 'black', lwd = 5, xlab = "Length (cm)", ylab = "Weight (kg)")
points(recfin_ca$recfin_length_cm, recfin_ca$AGENCY_WEIGHT, col = alpha('blue', 0.2), pch = 2)
lines(length, recfin_ests$A[2] * length ^ recfin_ests$B[2], col = 'blue', lwd = 5)
```

Read in GIS Data
```{r}
cb_gis <- read.csv("cb_gis.csv")
View(cb_gis)
```

GIS Analyses
```{r}
#Length, distance from land
cb_gis %>% 
  ggplot(aes(distance_land, length_cm)) +
  geom_point() +
  xlim(0, 3000) + 
  labs(x = "Distance from Land (m)", y = "Length (cm)")

#Weight, distance from land
cb_gis %>% 
  ggplot(aes(distance_land, weight_kg)) +
  geom_point() + 
  ylim(0, 8) + 
  xlim(0, 4000) + 
  labs(x = "Distance from Land (m)", y = "Weight (kg)")

#Length, depth
cb_gis %>% 
  ggplot(aes(depth, length_cm)) + 
  geom_point() + 
  scale_x_reverse() + 
  labs(x = "Depth (m)", y = "Length (cm)")

#Weight, depth
cb_gis %>% 
  ggplot(aes(depth, weight_kg)) + 
  geom_point() + 
  scale_x_reverse() + 
  ylim(0, 8) + 
  labs(x = "Depth (m)", y = "Weight (kg)")
```

Add mode column
```{r}
cb_md <- cb_gis %>% 
  mutate(fishing_mode = case_when(distance_land <= 115 ~ 'Shore/Jetty',
                                  distance_land > 115 ~ 'Boat'))
View(cb_md)

recfin_md <- recfin_ca %>% 
  mutate(recfin_mode = case_when(grepl("BOATS", RECFIN_MODE_NAME) ~ 'Boat',
                                 grepl("JETTY", RECFIN_MODE_NAME) ~ 'Shore/Jetty',
                                 grepl("BEACH", RECFIN_MODE_NAME) ~ 'Shore/Jetty'
                                   ))
View(recfin_md)
```

Fishing Mode Plots
```{r}
#Fishbrain
cb_md %>% 
  ggplot(aes(fishing_mode, fill = fishing_mode)) +
  geom_bar() + 
  labs(x = "Fishing Mode", y = "Count") +
  theme(legend.position = "none")

#RecFIN
recfin_md %>% 
  ggplot(aes(recfin_mode, fill = recfin_mode)) +
  geom_bar() +
  labs(x = "Fishing Mode", y = "Count") +
  theme(legend.position = "none")
```

Density plots
```{r}
#Length density plot - Fishbrain
fish_ca %>% 
  ggplot(aes(length_in_cm, color = district, fill = district)) +
  scale_color_viridis(discrete = TRUE) +
  geom_density(alpha = 0.1) + 
  labs(x = "Length (cm)")
#Length density plot - RecFIN
recfin_ca %>% 
  ggplot(aes(recfin_length_cm, color = district, fill = district)) +
  scale_color_viridis(discrete = TRUE) +
  geom_density(alpha = 0.1) +
  labs(x = "Length (cm)")

#Weight density plot - Fishbrain
fish_ca %>% 
  ggplot(aes(weight_in_kg, color = district, fill = district)) +
  scale_color_viridis(discrete = TRUE) +
  geom_density(alpha = 0.1) + 
  xlim(0, 8) +
  labs(x = "Weight (kg)")
#Weight density plot - RecFIN
recfin_ca %>% 
  ggplot(aes(AGENCY_WEIGHT, color = district, fill = district)) +
  scale_color_viridis(discrete = TRUE) +
  geom_density(alpha = 0.1)+ 
  labs(x = "Weight (kg)")
```

