---
title: "Fishbrain"
output:
  word_document: default
  html_document: default
  pdf_document: default
date: "2023-06-09"
---

Load packages
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

Read in Fishbrain data
```{r}
fishbrain <- read_csv("fishbrain.csv")
#View(fishbrain)
recfin <- read_csv("recfin.csv")
#View(recfin)
recfin_bio <- read_csv("recfin_bio.csv")
#View(recfin_bio)
```

Edit Fishbrain data
```{r}
fish_lw <- fishbrain %>% 
  filter(latitude > 34.45) %>% 
  mutate(district = case_when(latitude > 34.45 & latitude < 37.18 ~ 'Central',
                              latitude >= 37.18 & latitude < 38.91 ~ 'Bay Area',
                              latitude > 38.91 & latitude < 40.44 ~ 'Wine',
                              latitude > 40.44 ~ 'Redwood')) %>% 
  mutate_at(vars(district), as.factor) %>% 
  mutate(district = fct_relevel(district, c("Central", "Bay Area", "Wine", "Redwood"))) %>% 
  separate(caught_at_local_time, c('year', 'month', 'day')) %>% 
  filter(common_name == "Cabezon" | common_name == "Grass rockfish" | common_name == "Black rockfish" | common_name == "Copper rockfish" | common_name == "Brown rockfish" | common_name == "Kelp greenling" | common_name == "Blue rockfish" | common_name == "China rockfish" | common_name == "Olive rockfish" | common_name == "Rock greenling") %>% 
  mutate(length_in_mm = length_in_m * 1000) %>% 
  mutate(weight_in_g = weight_in_kg * 1000)
#View(fish_lw)
```

Edit RecFIN biological data
```{r}
recfin_lw <- recfin_bio %>% 
  filter(grepl("CENTRAL", RECFIN_PORT_NAME) | grepl("BAY AREA", RECFIN_PORT_NAME) | grepl("WINE", RECFIN_PORT_NAME) | grepl("REDWOOD", RECFIN_PORT_NAME)) %>% 
  separate(RECFIN_DATE, c("month", "day", "year")) %>% 
  mutate(district = case_when(grepl("CENTRAL", RECFIN_PORT_NAME) ~ "Central",
                              grepl("BAY AREA", RECFIN_PORT_NAME) ~ "Bay Area",
                              grepl("WINE", RECFIN_PORT_NAME) ~ "Wine",
                              grepl("REDWOOD", RECFIN_PORT_NAME) ~ "Redwood",
                              .default = RECFIN_PORT_NAME)) %>% 
  mutate_at(vars(district), as.factor) %>% 
  mutate(district = fct_relevel(district, c("Central", "Bay Area", "Wine", "Redwood"))) %>% 
  mutate(agency_weight_g = AGENCY_WEIGHT * 1000) 
#View(recfin_lw)
```

Species counts
```{r}
#Fishbrain
fish_count <- fish_lw %>% 
  group_by(common_name) %>% 
  tally() %>% 
  filter(n > 40)
View(fish_count)

#RecFIN
recfin_count <- recfin %>% 
  group_by(SPECIES_NAME) %>% 
  tally() %>% 
  filter(SPECIES_NAME == "Cabezon" | SPECIES_NAME == "Grass Rockfish" | SPECIES_NAME == "Black Rockfish" | SPECIES_NAME == "Copper Rockfish" | SPECIES_NAME == "Brown Rockfish" | SPECIES_NAME == "Kelp Greenling" | SPECIES_NAME == "Blue Rockfish" | SPECIES_NAME == "China Rockfish" | SPECIES_NAME == "Olive Rockfish" | SPECIES_NAME == "Rock Greenling")
View(recfin_count)
```

Weight and length analyses  - Fishbrain
```{r}
#Length by district - Fishbrain
fish_lw %>% 
  ggplot(aes(district, length_in_mm)) +
  geom_boxplot() +
  facet_wrap(vars(common_name)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "District", y = "Length (mm)") + 
  ylim(0, 1000)
#Length by district - RecFIN
recfin_lw %>% 
  ggplot(aes(district, RECFIN_LENGTH_MM)) +
  geom_boxplot() +
  facet_wrap(vars(SPECIES_NAME)) + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "District", y = "Length (mm)")

#Weight by district - Fishbrain
fish_lw %>% 
  ggplot(aes(district, weight_in_g)) +
  geom_boxplot() +
  facet_wrap(vars(common_name)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "District", y = "Weight (g)") +
  ylim(0, 6000)
#Weight by district - RecFIN
recfin_lw %>% 
  ggplot(aes(district, agency_weight_g)) +
  geom_boxplot() +
  facet_wrap(vars(SPECIES_NAME)) + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "District", y = "Weight (g)")
```

Weight-length relationship
```{r}
#Fishbrain
fish_lw %>% 
  ggplot(aes(length_in_mm, weight_in_g)) +
  geom_point() +
  facet_wrap(vars(common_name)) +
  ylim(0, 6000) + 
  xlim(0, 700) +
  labs(x = "Length (mm)", y = "Weight (g)")

#RecFIN
recfin_lw %>% 
  ggplot(aes(RECFIN_LENGTH_MM, agency_weight_g)) + 
  geom_point() +
  facet_wrap(vars(SPECIES_NAME)) + 
  labs(x = "Length (mm)", y = "Weight (g)")
```

Read in GIS Data
```{r}
fish_gis <- read.csv("fish_gis.csv")
View(fish_gis)
```

Edit GIS Data
```{r}
fish_gis %>% 
  mutate(length_in_cm = length_in_m * 100)
View(fish_gis)
```

Length and weight in relation to distance from land/depth
```{r}
#Length, distance from land
fish_gis %>% 
  ggplot(aes(distance_land, length_in_mm)) +
  geom_point() + 
  xlim(0, 2500) +
  labs(x = "Distance from Land (m)", y = "Length (mm)")

#Weight, distance from land
fish_gis %>% 
  ggplot(aes(distance_land, weight_in_kg)) +
  geom_point() + 
  ylim(0, 50) +
  xlim(0, 2500) +
  labs(x = "Distance from Land (m)", y = "Weight (kg)")

#Length, depth
fish_gis %>% 
  ggplot(aes(depth, length_in_mm)) +
  geom_point() + 
  scale_x_reverse() +
  xlim(0, -100) +
  labs(x = "Depth (m)", y = "Length (mm)")

#Weight, depth
fish_gis %>% 
  ggplot(aes(depth, weight_in_kg)) +
  geom_point() + 
  scale_x_reverse() +
  xlim(0, -100) +
  ylim(0, 125000) + 
  labs(x = "Depth (m)", y = "Weight (kg)")
```

Number of fish by district - Fishbrain & RecFIN
```{r}
#Black rockfish - Fishbrain
fish_dis_bla <- fish_lw %>% 
  filter(common_name == "Black rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_bla)
#Black rockfish - RecFIN
recfin_dis_bla <- recfin %>% 
  filter(SPECIES_NAME == "Black Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_bla)

#Blue rockfish - Fishbrain
fish_dis_blu <- fish_lw %>% 
  filter(common_name == "Blue rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_blu)
#Blue rockfish - RecFIN
recfin_dis_blu <- recfin %>% 
  filter(SPECIES_NAME == "Blue Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_blu)

#Brown rockfish - Fishbrain
fish_dis_br <- fish_lw %>% 
  filter(common_name == "Brown rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_br)
#Brown rockfish - RecFIN
recfin_dis_br <- recfin %>% 
  filter(SPECIES_NAME == "Brown Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_br)

#Cabezon - Fishbrain
fish_dis_ca <- fish_lw %>% 
  filter(common_name == "Cabezon") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_ca)
#Cabezon - RecFIN
recfin_dis_ca <- recfin %>% 
  filter(SPECIES_NAME == "Cabezon") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_ca)

#China rockfish - Fishbrain
fish_dis_ch <- fish_lw %>% 
  filter(common_name == "China rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_ch)
#China rockfish - RecFIN
recfin_dis_ch <- recfin %>% 
  filter(SPECIES_NAME == "China Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_ch)

#Copper rockfish - Fishbrain
fish_dis_co <- fish_lw %>% 
  filter(common_name == "Copper rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_co)
#Copper rockfish - RecFIN
recfin_dis_co <- recfin %>% 
  filter(SPECIES_NAME == "Copper Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_co)

#Grass rockfish - Fishbrain
fish_dis_gr <- fish_lw %>% 
  filter(common_name == "Grass rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_gr)
#Grass rockfish - RecFIN
recfin_dis_gr <- recfin %>% 
  filter(SPECIES_NAME == "Grass Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_gr)

#Kelp greenling - Fishbrain
fish_dis_kg <- fish_lw %>% 
  filter(common_name == "Kelp greenling") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_kg)
#Kelp greenling - RecFIN
recfin_dis_kg <- recfin %>% 
  filter(SPECIES_NAME == "Kelp Greenling") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_kg)

#Olive rockfish - Fishbrain
fish_dis_or <- fish_lw %>% 
  filter(common_name == "Olive rockfish") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_or)
#Olive rockfish - RecFIN
recfin_dis_or <- recfin %>% 
  filter(SPECIES_NAME == "Olive Rockfish") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_or)

#Rock greenling - Fishbrain
fish_dis_rg <- fish_lw %>% 
  filter(common_name == "Rock greenling") %>% 
  group_by(district) %>% 
  tally() 
View(fish_dis_rg)
#Rock greenling - RecFIN
recfin_dis_rg <- recfin %>% 
  filter(SPECIES_NAME == "Rock Greenling") %>% 
  group_by(DISTRICT_NAME) %>% 
  tally() 
View(recfin_dis_rg)
```

Number of fish by mode - RecFIN
```{r}
#Black rockfish
recfin_mode_bla <- recfin %>% 
  filter(SPECIES_NAME == "Black Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_bla)

#Blue rockfish
recfin_mode_blu <- recfin %>% 
  filter(SPECIES_NAME == "Blue Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_blu)

#Brown rockfish
recfin_mode_br <- recfin %>% 
  filter(SPECIES_NAME == "Brown Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_br)

#Cabezon
recfin_mode_ca <- recfin %>% 
  filter(SPECIES_NAME == "Cabezon") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_ca)

#China rockfish
recfin_mode_ch <- recfin %>% 
  filter(SPECIES_NAME == "China Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_ch)

#Copper rockfish
recfin_mode_co <- recfin %>% 
  filter(SPECIES_NAME == "Copper Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_co)

#Grass rockfish
recfin_mode_gr <- recfin %>% 
  filter(SPECIES_NAME == "Grass Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_gr)

#Kelp greenling
recfin_mode_kg <- recfin %>% 
  filter(SPECIES_NAME == "Kelp Greenling") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_kg)

#Olive rockfish
recfin_mode_or <- recfin %>% 
  filter(SPECIES_NAME == "Olive Rockfish") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_or)

#Rock greenling
recfin_mode_rg <- recfin %>% 
  filter(SPECIES_NAME == "Rock Greenling") %>% 
  group_by(RECFIN_MODE_NAME) %>% 
  tally() 
View(recfin_mode_rg)
```

